### ISSUE TITLE
Dépot projet ADEME 

### ISSUE THREAD

**Issue by GuillaumeAV** [chemins-de-la-transition/Vie-de-l-asso#41] opened 2020-07-06 15:40 UTC
Document de travail : https://docs.google.com/document/d/1nEDd5Uov5ZkdxRx_iYhRuoV26yD2Jf-HTp5U3S2_BoU/edit#

Dossier du projet : https://drive.google.com/drive/folders/18wHCDXFDT7MKOWCJ_j-7xo6RlOx7t8Xp?usp=sharing

**Comment by bouviermullerp** [comment] 2020-07-15 06:56
Duplicate of #35 - to be closed ? @GuillaumeAV

**Closed as completed** 2020-07-20 14:14 UTC
